projects:
  amplifypoc:
    schemaPath: amplify/backend/api/amplifypoc/build/schema.graphql
    includes:
      - uniquity/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        version: 3
        codeGenTarget: typescript
        generatedFileName: uniquity/src/graphql/API.ts
        docsFilePath: uniquity/src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
